// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: test.proto
#ifndef GRPC_test_2eproto__INCLUDED
#define GRPC_test_2eproto__INCLUDED

#include "test.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace helloworld {

class C_rpc final {
 public:
  static constexpr char const* service_full_name() {
    return "helloworld.C_rpc";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status c_do_something(::grpc::ClientContext* context, const ::helloworld::C_IN& request, ::helloworld::C_OUT* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::C_OUT>> Asyncc_do_something(::grpc::ClientContext* context, const ::helloworld::C_IN& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::C_OUT>>(Asyncc_do_somethingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::C_OUT>> PrepareAsyncc_do_something(::grpc::ClientContext* context, const ::helloworld::C_IN& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::C_OUT>>(PrepareAsyncc_do_somethingRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void c_do_something(::grpc::ClientContext* context, const ::helloworld::C_IN* request, ::helloworld::C_OUT* response, std::function<void(::grpc::Status)>) = 0;
      virtual void c_do_something(::grpc::ClientContext* context, const ::helloworld::C_IN* request, ::helloworld::C_OUT* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::C_OUT>* Asyncc_do_somethingRaw(::grpc::ClientContext* context, const ::helloworld::C_IN& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::C_OUT>* PrepareAsyncc_do_somethingRaw(::grpc::ClientContext* context, const ::helloworld::C_IN& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status c_do_something(::grpc::ClientContext* context, const ::helloworld::C_IN& request, ::helloworld::C_OUT* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::helloworld::C_OUT>> Asyncc_do_something(::grpc::ClientContext* context, const ::helloworld::C_IN& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::helloworld::C_OUT>>(Asyncc_do_somethingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::helloworld::C_OUT>> PrepareAsyncc_do_something(::grpc::ClientContext* context, const ::helloworld::C_IN& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::helloworld::C_OUT>>(PrepareAsyncc_do_somethingRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void c_do_something(::grpc::ClientContext* context, const ::helloworld::C_IN* request, ::helloworld::C_OUT* response, std::function<void(::grpc::Status)>) override;
      void c_do_something(::grpc::ClientContext* context, const ::helloworld::C_IN* request, ::helloworld::C_OUT* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::helloworld::C_OUT>* Asyncc_do_somethingRaw(::grpc::ClientContext* context, const ::helloworld::C_IN& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::helloworld::C_OUT>* PrepareAsyncc_do_somethingRaw(::grpc::ClientContext* context, const ::helloworld::C_IN& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_c_do_something_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status c_do_something(::grpc::ServerContext* context, const ::helloworld::C_IN* request, ::helloworld::C_OUT* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_c_do_something : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_c_do_something() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_c_do_something() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status c_do_something(::grpc::ServerContext* /*context*/, const ::helloworld::C_IN* /*request*/, ::helloworld::C_OUT* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestc_do_something(::grpc::ServerContext* context, ::helloworld::C_IN* request, ::grpc::ServerAsyncResponseWriter< ::helloworld::C_OUT>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_c_do_something<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_c_do_something : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_c_do_something() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::helloworld::C_IN, ::helloworld::C_OUT>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::helloworld::C_IN* request, ::helloworld::C_OUT* response) { return this->c_do_something(context, request, response); }));}
    void SetMessageAllocatorFor_c_do_something(
        ::grpc::MessageAllocator< ::helloworld::C_IN, ::helloworld::C_OUT>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::helloworld::C_IN, ::helloworld::C_OUT>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_c_do_something() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status c_do_something(::grpc::ServerContext* /*context*/, const ::helloworld::C_IN* /*request*/, ::helloworld::C_OUT* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* c_do_something(
      ::grpc::CallbackServerContext* /*context*/, const ::helloworld::C_IN* /*request*/, ::helloworld::C_OUT* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_c_do_something<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_c_do_something : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_c_do_something() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_c_do_something() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status c_do_something(::grpc::ServerContext* /*context*/, const ::helloworld::C_IN* /*request*/, ::helloworld::C_OUT* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_c_do_something : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_c_do_something() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_c_do_something() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status c_do_something(::grpc::ServerContext* /*context*/, const ::helloworld::C_IN* /*request*/, ::helloworld::C_OUT* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestc_do_something(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_c_do_something : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_c_do_something() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->c_do_something(context, request, response); }));
    }
    ~WithRawCallbackMethod_c_do_something() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status c_do_something(::grpc::ServerContext* /*context*/, const ::helloworld::C_IN* /*request*/, ::helloworld::C_OUT* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* c_do_something(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_c_do_something : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_c_do_something() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::helloworld::C_IN, ::helloworld::C_OUT>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::helloworld::C_IN, ::helloworld::C_OUT>* streamer) {
                       return this->Streamedc_do_something(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_c_do_something() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status c_do_something(::grpc::ServerContext* /*context*/, const ::helloworld::C_IN* /*request*/, ::helloworld::C_OUT* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedc_do_something(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::helloworld::C_IN,::helloworld::C_OUT>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_c_do_something<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_c_do_something<Service > StreamedService;
};

class Py_rpc final {
 public:
  static constexpr char const* service_full_name() {
    return "helloworld.Py_rpc";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status py_do_something(::grpc::ClientContext* context, const ::helloworld::PY_IN& request, ::helloworld::PY_OUT* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::PY_OUT>> Asyncpy_do_something(::grpc::ClientContext* context, const ::helloworld::PY_IN& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::PY_OUT>>(Asyncpy_do_somethingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::PY_OUT>> PrepareAsyncpy_do_something(::grpc::ClientContext* context, const ::helloworld::PY_IN& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::PY_OUT>>(PrepareAsyncpy_do_somethingRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void py_do_something(::grpc::ClientContext* context, const ::helloworld::PY_IN* request, ::helloworld::PY_OUT* response, std::function<void(::grpc::Status)>) = 0;
      virtual void py_do_something(::grpc::ClientContext* context, const ::helloworld::PY_IN* request, ::helloworld::PY_OUT* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::PY_OUT>* Asyncpy_do_somethingRaw(::grpc::ClientContext* context, const ::helloworld::PY_IN& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::PY_OUT>* PrepareAsyncpy_do_somethingRaw(::grpc::ClientContext* context, const ::helloworld::PY_IN& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status py_do_something(::grpc::ClientContext* context, const ::helloworld::PY_IN& request, ::helloworld::PY_OUT* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::helloworld::PY_OUT>> Asyncpy_do_something(::grpc::ClientContext* context, const ::helloworld::PY_IN& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::helloworld::PY_OUT>>(Asyncpy_do_somethingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::helloworld::PY_OUT>> PrepareAsyncpy_do_something(::grpc::ClientContext* context, const ::helloworld::PY_IN& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::helloworld::PY_OUT>>(PrepareAsyncpy_do_somethingRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void py_do_something(::grpc::ClientContext* context, const ::helloworld::PY_IN* request, ::helloworld::PY_OUT* response, std::function<void(::grpc::Status)>) override;
      void py_do_something(::grpc::ClientContext* context, const ::helloworld::PY_IN* request, ::helloworld::PY_OUT* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::helloworld::PY_OUT>* Asyncpy_do_somethingRaw(::grpc::ClientContext* context, const ::helloworld::PY_IN& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::helloworld::PY_OUT>* PrepareAsyncpy_do_somethingRaw(::grpc::ClientContext* context, const ::helloworld::PY_IN& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_py_do_something_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status py_do_something(::grpc::ServerContext* context, const ::helloworld::PY_IN* request, ::helloworld::PY_OUT* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_py_do_something : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_py_do_something() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_py_do_something() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status py_do_something(::grpc::ServerContext* /*context*/, const ::helloworld::PY_IN* /*request*/, ::helloworld::PY_OUT* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestpy_do_something(::grpc::ServerContext* context, ::helloworld::PY_IN* request, ::grpc::ServerAsyncResponseWriter< ::helloworld::PY_OUT>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_py_do_something<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_py_do_something : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_py_do_something() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::helloworld::PY_IN, ::helloworld::PY_OUT>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::helloworld::PY_IN* request, ::helloworld::PY_OUT* response) { return this->py_do_something(context, request, response); }));}
    void SetMessageAllocatorFor_py_do_something(
        ::grpc::MessageAllocator< ::helloworld::PY_IN, ::helloworld::PY_OUT>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::helloworld::PY_IN, ::helloworld::PY_OUT>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_py_do_something() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status py_do_something(::grpc::ServerContext* /*context*/, const ::helloworld::PY_IN* /*request*/, ::helloworld::PY_OUT* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* py_do_something(
      ::grpc::CallbackServerContext* /*context*/, const ::helloworld::PY_IN* /*request*/, ::helloworld::PY_OUT* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_py_do_something<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_py_do_something : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_py_do_something() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_py_do_something() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status py_do_something(::grpc::ServerContext* /*context*/, const ::helloworld::PY_IN* /*request*/, ::helloworld::PY_OUT* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_py_do_something : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_py_do_something() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_py_do_something() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status py_do_something(::grpc::ServerContext* /*context*/, const ::helloworld::PY_IN* /*request*/, ::helloworld::PY_OUT* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestpy_do_something(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_py_do_something : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_py_do_something() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->py_do_something(context, request, response); }));
    }
    ~WithRawCallbackMethod_py_do_something() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status py_do_something(::grpc::ServerContext* /*context*/, const ::helloworld::PY_IN* /*request*/, ::helloworld::PY_OUT* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* py_do_something(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_py_do_something : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_py_do_something() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::helloworld::PY_IN, ::helloworld::PY_OUT>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::helloworld::PY_IN, ::helloworld::PY_OUT>* streamer) {
                       return this->Streamedpy_do_something(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_py_do_something() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status py_do_something(::grpc::ServerContext* /*context*/, const ::helloworld::PY_IN* /*request*/, ::helloworld::PY_OUT* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedpy_do_something(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::helloworld::PY_IN,::helloworld::PY_OUT>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_py_do_something<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_py_do_something<Service > StreamedService;
};

}  // namespace helloworld


#endif  // GRPC_test_2eproto__INCLUDED
