# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='helloworld',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ntest.proto\x12\nhelloworld\"\x12\n\x04\x43_IN\x12\n\n\x02\x63\x61\x18\x01 \x01(\t\"\x13\n\x05\x43_OUT\x12\n\n\x02\x63\x62\x18\x01 \x01(\t\"\x14\n\x05PY_IN\x12\x0b\n\x03pya\x18\x01 \x01(\t\"\x15\n\x06PY_OUT\x12\x0b\n\x03pyb\x18\x01 \x01(\t2@\n\x05\x43_rpc\x12\x37\n\x0e\x63_do_something\x12\x10.helloworld.C_IN\x1a\x11.helloworld.C_OUT\"\x00\x32\x44\n\x06Py_rpc\x12:\n\x0fpy_do_something\x12\x11.helloworld.PY_IN\x1a\x12.helloworld.PY_OUT\"\x00\x62\x06proto3'
)




_C_IN = _descriptor.Descriptor(
  name='C_IN',
  full_name='helloworld.C_IN',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ca', full_name='helloworld.C_IN.ca', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=44,
)


_C_OUT = _descriptor.Descriptor(
  name='C_OUT',
  full_name='helloworld.C_OUT',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cb', full_name='helloworld.C_OUT.cb', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=65,
)


_PY_IN = _descriptor.Descriptor(
  name='PY_IN',
  full_name='helloworld.PY_IN',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pya', full_name='helloworld.PY_IN.pya', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=87,
)


_PY_OUT = _descriptor.Descriptor(
  name='PY_OUT',
  full_name='helloworld.PY_OUT',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pyb', full_name='helloworld.PY_OUT.pyb', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=110,
)

DESCRIPTOR.message_types_by_name['C_IN'] = _C_IN
DESCRIPTOR.message_types_by_name['C_OUT'] = _C_OUT
DESCRIPTOR.message_types_by_name['PY_IN'] = _PY_IN
DESCRIPTOR.message_types_by_name['PY_OUT'] = _PY_OUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

C_IN = _reflection.GeneratedProtocolMessageType('C_IN', (_message.Message,), {
  'DESCRIPTOR' : _C_IN,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.C_IN)
  })
_sym_db.RegisterMessage(C_IN)

C_OUT = _reflection.GeneratedProtocolMessageType('C_OUT', (_message.Message,), {
  'DESCRIPTOR' : _C_OUT,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.C_OUT)
  })
_sym_db.RegisterMessage(C_OUT)

PY_IN = _reflection.GeneratedProtocolMessageType('PY_IN', (_message.Message,), {
  'DESCRIPTOR' : _PY_IN,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.PY_IN)
  })
_sym_db.RegisterMessage(PY_IN)

PY_OUT = _reflection.GeneratedProtocolMessageType('PY_OUT', (_message.Message,), {
  'DESCRIPTOR' : _PY_OUT,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.PY_OUT)
  })
_sym_db.RegisterMessage(PY_OUT)



_C_RPC = _descriptor.ServiceDescriptor(
  name='C_rpc',
  full_name='helloworld.C_rpc',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=112,
  serialized_end=176,
  methods=[
  _descriptor.MethodDescriptor(
    name='c_do_something',
    full_name='helloworld.C_rpc.c_do_something',
    index=0,
    containing_service=None,
    input_type=_C_IN,
    output_type=_C_OUT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_C_RPC)

DESCRIPTOR.services_by_name['C_rpc'] = _C_RPC


_PY_RPC = _descriptor.ServiceDescriptor(
  name='Py_rpc',
  full_name='helloworld.Py_rpc',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=178,
  serialized_end=246,
  methods=[
  _descriptor.MethodDescriptor(
    name='py_do_something',
    full_name='helloworld.Py_rpc.py_do_something',
    index=0,
    containing_service=None,
    input_type=_PY_IN,
    output_type=_PY_OUT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PY_RPC)

DESCRIPTOR.services_by_name['Py_rpc'] = _PY_RPC

# @@protoc_insertion_point(module_scope)
